services:
  postgres:
    image: postgres:latest  # Replace with a specific tag if needed
    hostname: postgres
    container_name: postgres
    networks:
      - virtual-net
    environment:
      POSTGRES_PASSWORD: postgres  # Set password environment variable
      POSTGRES_DB: spring_boot_gradle_java_multi_module_boilerplate  # Set database name environment variable
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for Postgres data

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - virtual-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    networks:
      - virtual-net
    environment:
      KAFKA_kafka_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  schemaregistry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    networks:
      - virtual-net
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # Java Application Service
  application:
    build: .  # Replace with the path to your Java application Dockerfile
    hostname: application
    container_name: application
    depends_on:
      - schemaregistry
      - postgres
    ports:
      - "8080:8080"  # Replace with your application port (if applicable)
    networks:
      - virtual-net
    environment:
      POSTGRES_HOST: host.docker.internal  # Using recommended method
      # Alternatively (if not using host.docker.internal)
      # POSTGRES_HOST: 172.17.0.1  # Replace with your bridge IP if needed
      POSTGRES_DATABASE: spring_boot_gradle_java_multi_module_boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081
      AZURE_AD_CREDENTIAL_CLIENT_ID:
      AZURE_AD_APP_ID_URI:

networks:
  virtual-net:

volumes:
  postgres_data: {}