spring:
  application:
    name: spring-boot-gradle-java-boilerplate

  # Module(s): microsoft-entra-ID-access-resource-server-example
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: ${AZURE_CLIENT_ID}
        app-id-uri: ${APP_ID_URI}